### ISSUE TITLE
Penyesuaian tampilan artikel terbaru

### ISSUE THREAD

**Issue by hak11** [phpid-jakarta/phpid-jakarta.github.io#105]
untuk tampilan di Atikel Terbaru di Home terlihan kurang rapih,  butuh penyesuaian seperti readmore atau kesepakatan max height/width pada gambar utama

![screenshot from 2017-05-13 09-20-40](https://cloud.githubusercontent.com/assets/14852163/26021720/008c6d7c-37be-11e7-95dc-be12bb6a67ca.png)

**Comment by ekojs** [comment]
boleh nih idenya, monggo kasih rekomendasi aja bagusnya gimana.
coba diskusi sama @muhibbudins ya @hak11
