### ISSUE TITLE
Tambahkan informasi di footer

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/phpid-jakarta.github.io#18]
Saya kepikiran untuk menambah beberapa informasi di footer seperti
+ Komunitas sahabat kaya phpindonesia pusat, phpindonesia regional lain, dll
+ Link ke kategori yg mau di highlight seperti event, meetup, kulwap, tutorial, dll

Mesti di arrange lagi juga html nya.
Sekarang masih apa adanya aja

**Comment by hak11** [comment]
terkait dengan issue ini @muhibbudins  udah bikin mockupnya yang kemaren di share, mau dibkin gitu aja apa engga @mazipan atau mau improve?

kalo udah oke nnt saya assignees diticket ini

**Comment by mazipan** [comment]
Iya, tapi kecil bgt gambarnya.
Pasti agak lama juga ya nunggu nya, sibuk sepertinya orangnya.
Tapi konsepnya sih sama.
Dibuat kaya beberapa kolom, terus ada info yg lebih banyak.
Kalo mau coba utak-atik monggo om @hak11, boleh bgt.

**Comment by hak11** [comment]
oke saya coba dulu ya @mazipan

**Comment by mazipan** [comment]
Ini saya close dulu ya,
kalo ada yang mau dibenerin bisa buka issue baru.
