### ISSUE TITLE
Buat category and tag 

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/phpid-jakarta.github.io#19]
Saya baca artikel ini
https://codinfox.github.io/dev/2015/03/06/use-tags-and-categories-in-your-jekyll-based-github-pages/

Serta kode ini
https://github.com/codinfox/codinfox-lanyon/tree/dev/blog

Mungkin mau dicoba diterapkan

**Comment by ekojs** [comment]
- [x] Issue https://github.com/phpid-jakarta/phpid-jakarta.github.io/pull/24 udah saya merge, mas @hak11 menambahkan **Style** pada tagnya.

- [ ] Untuk Issue https://github.com/phpid-jakarta/phpid-jakarta.github.io/pull/23 rencana akan saya close. Karena pull dari branch user:develop ke master tidak ada perubahan.

**Comment by ekojs** [comment]
Issue #26 perlu direview untuk styling menunya.

**Comment by hak11** [comment]
oke @ekojs

**Comment by mazipan** [comment]
yang tag udah sama om @hak11.
tapi category belum ditampilkan di artikel page.

**Comment by mazipan** [comment]
Tolong ditampilkan juga post tersebut ada di category apa ya @hak11 atau @ekojs

**Comment by ekojs** [comment]
Telah diperbaiki di #36 . Issue ditutup.
