### ISSUE TITLE
Style untuk pagination

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/phpid-jakarta.github.io#20]
Om @ekojs sudah buatkan logic untuk pagination.
Tinggal setup style yg lebih menarik saja.
Terserah mau model apa sih.
Untuk Developement bisa dikecilkan dulu angka pagination di config.yml nya ya.

**Comment by hak11** [comment]
tekait issu ini gimana @mazipan , pagination yang mananya ya

**Comment by mazipan** [comment]
Pagination artikel @hak11 , kalo nyoba di lokal bisa di kecilin settingan pagination-nya di config.yml
atau buat beberapa file post dummy

**Comment by hak11** [comment]
oke pagination mau dibkin max limit berapa yang muncul mas ?
