### ISSUE TITLE
Buat archieve page

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/phpid-jakarta.github.io#25]
Archieve page intinya adalah seperti daftar isi atau daftar semua artikel yang ada.
Biasa ditata berdasarkan date publikasi ataupun bisa ditata berdasarkan kategori artikel.
Saya sih prefer berdasarkan kategori saja.

**Comment by ekojs** [comment]
Kayak sitemap maksudnya ?

**Comment by mazipan** [comment]
Iya, model itu.
Tapi ini dibuat seperti artikel gitu om.

Contoh :
https://mazipanneh.wordpress.com/2011/07/25/daftar-isi/

Memudahkan buat visitor baru, karena yg ditampilkan di homepage kan hanya 5 last post saja.
Yang udah lama bisa tenggelam.

**Comment by mazipan** [comment]
Kalo sitemap sendiri sudah bisa di generate via plugin.

http://jakarta.phpindonesia.or.id/sitemap.xml

**Comment by mazipan** [comment]
has been init by @ekojs but still need styling.
will be handled by me.
