### ISSUE TITLE
Broken Link saat menu diakses dari tampilan post

### ISSUE THREAD

**Issue by ekojs** [phpid-jakarta/phpid-jakarta.github.io#30]
Ketika masuk tampilan post setelah **Read More**, kemudian akses menu Arsip. Maka hasilnya 404 Not Found (Broken Link)

**Comment by mazipan** [comment]
Bisa ditambahkan / di link nya om @ekojs di menu.yml nya

**Comment by ekojs** [comment]
Sudah di perbaiki om disini #32
