### ISSUE TITLE
Tag di artikel mengarah ke link yang salah.

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/phpid-jakarta.github.io#31]
Seharusnya kan mengarah ke daftar artikel dengan tag yang sama.

**Comment by ekojs** [comment]
Klo di jekyll kalo mau dibuat tampil dengan tag yang sama, kita harus bikin file **nama_tag**.html sebagai landingnya om.
Apa kita ga pake link yang dari **arsip.html** aja ? atau mau di point ke halaman arsip ?

**Comment by mazipan** [comment]
Tapi kalo pake nama_tag.html jadi gak dinamis kan ya ?
Mesti buat satu2 tiap ada yang baru.
Bisa ke arsip tapi tambahkan hash id nya biar bisa langsung fokus ke tag yg bersangkutan.

**Comment by ekojs** [comment]
Nah itu dia om. Oke klo gitu aq buatkan hash tag idnya. 👍
