### ISSUE TITLE
Buat page 404

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/phpid-jakarta.github.io#37]
http://jakarta.phpindonesia.or.id/program_kerja.html
Sekarang masih default dari gh-pages

**Comment by ekojs** [comment]
nyahahaha.... 💃

**Comment by 3Shoka** [comment]
kalo mau bikin halaman 404 itu bikin file nya dimana ?

**Comment by mazipan** [comment]
Summon Kang @ekojs

**Comment by ekojs** [comment]
@3Shoka ini dokumentasi caranya [https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/](https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/)
