### ISSUE TITLE
Tambahkan beberapa pengurus di akun official.

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/phpid-jakarta.github.io#41]
Web ini menggunakan beberapa akun seperti Disqus, Google Analytics, dll yang alangkah baiknya kalau tidak hanya diakses oleh satu orang karena beberapa setup tentu akan memudahkan kalau tidak bergantung pada satu orang.
Minta bantuan om @ekojs buat nambahin beberapa pengurus ke akun nya ya.

**Comment by ekojs** [comment]
Oke om, tolong di list email yg perlu ditambahkan yak. :D

**Comment by mazipan** [comment]
Irfan Maulana (mazipanneh@gmail.com)

**Comment by mazipan** [comment]
@3Shoka juga butuh kali ?

**Comment by 3Shoka** [comment]
Ashokani (ashzoea@gmail.com)

**Comment by ekojs** [comment]
Sudah Aq tambahkan ke property **analytics** di phpid-jakarta yak, silahkan cek email. Untuk admin disqus, perlu punya akun disqus. Tolong di list nama akun **disqus** nya. :smiley:

**Comment by mazipan** [comment]
Disquss Profile Url : 

https://disqus.com/by/mazipan/

Email : mazipanneh@gmail.com

**Comment by ekojs** [comment]
Udah aq tambahkan om akun disqusnya sebagai admin.
