### ISSUE TITLE
Submit ke search engine

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/phpid-jakarta.github.io#42]
Minta submit ke google web master, yandex, sama Bing kalo sempat.

https://www.google.com/webmasters/tools/home
https://webmaster.yandex.com/
http://www.bing.com/toolbox/webmaster

**Comment by ekojs** [comment]
- [ ] Setup Google Web Master
- [ ] Setup Yandex
- [ ] Setup Bing
