### ISSUE TITLE
Sort date in Daftar Isi from newer to older post

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/phpid-jakarta.github.io#46]
Post should be sort from newer first

**Comment by ekojs** [comment]
Oke. Nanti saya PR sekalian fixing bug issue #56 . :+1:  :smiley: 
untuk sorting from newer :

```
{% assign sorted = (site.posts | sort: 'date' | reverse) %}
{% for post in sorted %}
bla.. bla..
```

**Comment by mazipan** [comment]
sudah di kerjain, butuh di cek ulang.
kalo sudah oke, tolong close issue nya juga

**Comment by ekojs** [comment]
Oke om.
