### ISSUE TITLE
Request add account ke Google Search Console

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/phpid-jakarta.github.io#69]
Yang saya tau Google Search Console bisa menambahkan​ beberapa akun untuk mengurusi satu site.
Jika bisa minta tambahkan akun saya ya om @ekojs.

Email : mazipanneh@gmail.com

**Comment by mazipan** [comment]
https://www.dropbox.com/sh/ggb3swmo8r23tl8/AAC7HMZ__0bZi_Wcsdud9aA8a?dl=0

File HTML Google Search Console

**Comment by ekojs** [comment]
aq lihat udah ditambahkan yak ?

**Comment by mazipan** [comment]
File html ini perlu ada di root https://phpid-jakarta.github.io
Minta tolong ditambahkan

**Comment by ekojs** [comment]
- [ ] in progress..
