### ISSUE TITLE
Create new page - members

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/phpid-jakarta.github.io#71]
Isinya list member.
Looping pake .yml file kaya model menu.
Nanti di homepage kita tampilkan 5 member/pengurus.
Nanti kasih link lihatt semua member yang ngarahin ke page ini

**Comment by muhibbudins** [comment]
Isinya apa aja @mazipan ? Foto, nama, jabatan or something else?

**Comment by mazipan** [comment]
Sementara mungkin nama, foto, jabatan dan dimana kerjanya.
Next bisa tambahin little bio.
Untuk Development bisa buat dummy data dulu @muhibbudins.
Ambil aja foto siapa... 😂😂😂

**Comment by mazipan** [comment]
Kalo buat page nya ribet nanti dibantu saya atau om @ekojs.
Saya baru bisa online bantuin kalo di kantor.
Om @muhibbudins bisa pake data dummy dulu gak perlu setup Dan looping.
Takut kelamaan.
Tapi kalau mau sekalian, ya boleh bgt lah

**Comment by muhibbudins** [comment]
Oke om siap, command accepted saya coba buat setelah si homepagenya selesai ya. :smiley:

**Comment by mazipan** [comment]
👍👍👍

**Comment by ekojs** [comment]
Uda saya buat page untuk member di #76. monggo klo uda sesuai bisa diclose issue ini. :smiley:
