### ISSUE TITLE
Ubah atau hapus dummy konten bila sudah fix

### ISSUE THREAD

**Issue by ekojs** [phpid-jakarta/phpid-jakarta.github.io#82]
- [ ] Dummy pada caption slider.
- [ ] Dummy pada List member.
- [ ] Dummy pada Sponsorship. Mungkin perlu ditambah **Powered By Github Pages** kali yak ?

**Comment by hak11** [comment]
mengenai data sponsorship yang sekarang itu saya ambil dari gambar di forum php indonesia @ekojs , boleh nanti saya tambahin informasi powed by github
