### ISSUE TITLE
Rekap data member

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/phpid-jakarta.github.io#89]
Tolong di rekap data member yang akan ditampilkan, sementara informasi yang akan ditampilkan :

----------------------------------------------------------------------------------
+ Nama Lengkap
+ Pekerjaan
+ Sosial Media : Facebook, Twitter, Instagram, Github (*Ini aja, jangan kebanyakan)
+ Foto Profile Url
----------------------------------------------------------------------------------

Pisahkan antara pengurus dengan member biasa.

**Comment by mazipan** [comment]
Ukuran profile picture kalo bisa kurang lebih 500x500 biar gak terlalu gede

**Comment by 3Shoka** [comment]
gimana kalo bikin google form buat isi ulang data member sesuai format itu ?

**Comment by ekojs** [comment]
@3Shoka, klo bisa update aja yg ditrello. nanti klo mereka ngisi google form terus yg mau updatin data mereka di trello siapa ?

**Comment by 3Shoka** [comment]
Yg di trello ya biar gitu aja, kita kan butuh nya buat di web

**Comment by mazipan** [comment]
Saya setuju sama @3Shoka, buat gForm.
Sekarang sih data buat di web ini kurang lebih kaya contoh ini

+ name: "Irfan Maulana"
+ jobs: "Software Development Engineer at Blibli.com"
+ image: "/assets/images/member/member/irfan-maulana.jpg"
+ fb_url: "https://facebook.com/mazipanneh"
+ tw_url: "https://twitter.com/Maz_Ipan"
+ gh_url: "https://github.com/mazipan"
+ ins_url: "https://instagram.com/maz_ipan"

**Comment by 3Shoka** [comment]
kayaknya perlu url linkedin juga deh @mazipan 

aku dah bikin form nya, tinggal nunggu kesepakatan temen-temen gimana ?

**Comment by mazipan** [comment]
boleh tuh ditambahin, nanti url form nya tolong di comment di issue ini juga ya @3Shoka

**Comment by mazipan** [comment]
Trello link : https://trello.com/b/kK2gsS9o/team-chapter-jakarta

Google Form : https://goo.gl/forms/6xw8PaygRzk0E9ym1

**Comment by mazipan** [comment]
https://docs.google.com/forms/d/1cO0cga8-R-trNWorwTsF64DUc_BvwxZZiAp8gnq3wwg/edit?ts=59288121#responses

Response 👆
